Added invoices and adjusted code to new db logic
Ghostyshka/VeterinaryClinicsManagementProject pull request #4
Opened 2024-10-02 17:34 UTC by Ghostyshka

2024-10-04 10:39 UTC, denyshfive requested changes

2024-10-04 10:39 UTC, denyshfive commented on VetClinicManagament/Core/Domain/Entities/Invoice.cs
> +    public Visit Visit { get; set; } // Single Visit Reference
````// Single Visit Reference```` 
no need for such comments

2024-10-04 10:39 UTC, denyshfive commented on VetClinicManagament/Core/Domain/Entities/Invoice.cs
> +    public ICollection<InvoiceItem> InvoiceItems { get; set; } // Collection of Invoice Items
no need for such comments

2024-10-04 10:39 UTC, denyshfive commented on VetClinicManagament/Core/Domain/Entities/Medicals.cs
> +    //public MedicalsType MedicalsType { get; set; }
please fix or remove commented code

2024-10-04 10:39 UTC, denyshfive commented on VetClinicManagament/Core/Domain/Entities/MedicalsType.cs
> +    //public ICollection<Medicals> Medicals{ get; set; }
please fix or remove commented code

2024-10-04 10:39 UTC, denyshfive commented on VetClinicManagament/Core/Domain/Entities/Services.cs
> +    //public ICollection<Treatment> Treatments { get; set; }
please fix or remove commented code

2024-10-04 10:39 UTC, denyshfive commented on VetClinicManagament/Core/Domain/Entities/TreatmentPlanItem.cs
> +    //public int AnimalId { get; set; }
please fix or remove commented code

2024-10-04 10:39 UTC, denyshfive commented on VetClinicManagament/Core/Domain/Models/Dtos/AnimalDto.cs
> +    public string EmployeeEmail { get; set; }
why do you need EmployeeEmail here?

2024-10-04 10:39 UTC, denyshfive commented on VetClinicManagament/Core/Domain/Models/Dtos/AnimalDto.cs
> +    public int SpeciesId { get; set; }
why do you need SpeciesId if it already will be in the Specie property below?

2024-10-04 10:39 UTC, denyshfive commented on VetClinicManagament/Core/Domain/Models/AnimalModel.cs
> +public class AnimalModel        // need to refactor
please make it TODO comment and try to implement "TODO" comments before creating pull requests

2024-10-04 10:39 UTC, denyshfive commented on VetClinicManagament/Core/Domain/Repositories/IPersonRepository.cs
> +    //Task GetPersonByEmailAsync(object email); // Optional, for non-generic access
please remove commented code

2024-10-04 10:39 UTC, denyshfive commented on VetClinicManagament/Core/Domain/Repositories/IUserRepository.cs
> +    //Task<UserModel> GetUserByEmailAsync(string email);
please remove commented code

2024-10-04 10:39 UTC, denyshfive commented on VetClinicManagament/Infrastructure/Persistence/Repositories/PersonRepository.cs
> +    //public async Task<T?> GetPersonByEmailAsync<T>(string email) where T : class
please remove commented code

2024-10-04 10:39 UTC, denyshfive commented on VetClinicManagament/Infrastructure/Persistence/Configurations/AnimalOwnersConfiguration.cs
> +        //check to:do
please remove

2024-10-04 10:39 UTC, denyshfive commented on VetClinicManagament/Infrastructure/Persistence/Configurations/InvoiceConfiguration.cs
> +        builder.HasMany(i => i.Visits)  // invoice has many visits
please remove comments

2024-10-04 10:39 UTC, denyshfive commented on VetClinicManagament/Infrastructure/Persistence/Configurations/InvoiceItemConfiguration.cs
> +        builder.HasOne(it => it.Invoice)  // each InvoiceItem belongs to one Invoice
please remove comments

2024-10-04 10:39 UTC, denyshfive commented on VetClinicManagament/Infrastructure/Persistence/Configurations/TreatmentPlanConfiguration.cs
> +        //builder.HasOne(tp => tp.Animal)
please fix or remove commented code

2024-10-07 11:14 UTC, Ghostyshka commented on VetClinicManagament/Core/Domain/Models/AnimalModel.cs
> +public class AnimalModel        // need to refactor
okay, I understood
thanks for pointing that out

2024-10-07 12:11 UTC, Ghostyshka commented on VetClinicManagament/Core/Domain/Models/Dtos/AnimalDto.cs
> +    public string EmployeeEmail { get; set; }
deleted, thx

2024-10-07 12:11 UTC, Ghostyshka commented on VetClinicManagament/Core/Domain/Models/Dtos/AnimalDto.cs
> +    public int SpeciesId { get; set; }
deleted, thx

2024-10-07 12:27 UTC, merged